### ISSUE TITLE
Harmochord

### ISSUE THREAD

**Issue by tomasmark79** [j74/HarmoTools-plugins-for-Ableton-Live-#1]
I use Harmochord to monitor MIDI chords. I've found that problems arise when Harmochord is on multiple tracks, inadvertently mixing all MIDI in all instances of Harmochord. So chaos is depicted.

I would expect that for each track, Harmochord will only show the MIDI corresponding to that track on which Harmochord is located. Currently, I solve the problem by using Harmochord on only one track. However, I use a template where there is a new MIDI track.

Am I missing something?
Thanks

**Comment by j74** [comment]
This is not a bug. Harmochoord is meant to be used once and it commands 
all the filter devices in any tracks.
What you can do is put it on various tracks and alternate with some 
automation which istance is active, one at a time.
Gr/Fabrizio
